### ISSUE TITLE
`.. note::` is not recognized by VSCode

### ISSUE THREAD

**Issue by haiiliin** [haiiliin/abqpy#1359]
### Problem

`.. note::` is not recognized by VSCode. A similar issue is the `.. code-block::` in #1265, it can be fixed by using `::` instead of `.. code-block::`.

### Possible Solutions

- [ ] Simply remove the `.. note::` environment
- [ ] Using the `numpydoc` [`Notes`](https://numpydoc.readthedocs.io/en/latest/format.html#notes) section

**Comment by Diogo-Rossi** [comment]
There are others directives, less common, that are also not recognized by VS Code (`.. versionadded::`, `.. autolink-skip::`,`...`). I think that is because VS Code can't render directives at all.

> Using the `numpydoc` [`Notes`](https://numpydoc.readthedocs.io/en/latest/format.html#notes) section

Replace `.. code-block::` by `::` and `.. note::` by the `numpydoc` [`Notes`](https://numpydoc.readthedocs.io/en/latest/format.html#notes) will help a lot in the current state of VS Code, even more because that directives are the most used.

However, I think this is a limitation of VS Code itself, and could be neglected if bring issues to `abqpy`, I mean, if `abqpy` get limitations due to VS Code. Besides, [there is already an open discussion very up voted in `pylance` repository]() that may solve the problem that VS Code has with Sphinx.

Therefore, I think this modification could still be done only if brigs advantages to `abqpy`. I mean: simplify the code, make it easy to write, and so on...

**Comment by haiiliin** [comment]
Actually, at first, I am using the `Notes` section, but sphinx will always place the `Notes` section after the parameters, even if it is before the parameters in the source code, which is very inconvenient to check the documentation.

**Comment by Diogo-Rossi** [comment]
> Actually, at first, I am using the `Notes` section, but sphinx will always place the `Notes` section after the parameters, even if it is before the parameters in the source code, which is very inconvenient to check the documentation.

Exactly, directives are a more robust way to use Sphinx. (I just update the link in my [previous post](https://github.com/haiiliin/abqpy/issues/1359#issuecomment-1246673645))
